const express=require('express');
const {pool}=require('../db');
const {validateJurisdiction,validateTransition}=require('../domain/claimGuidePolicy');
const router=express.Router();
const tenantOf=(req)=>String(req.user.tenant_id||req.user.id);

router.post('/',async(req,res,next)=>{const client=await pool.connect();try{const jurisdiction=validateJurisdiction(req.body.jurisdiction||{});if(!req.body.idempotency_key||!req.body.disclaimer_accepted_at||!req.body.consent)throw new Error('idempotency_key, disclaimer acceptance, and consent are required');const tenant=tenantOf(req);await client.query('BEGIN');const source=await client.query(`INSERT INTO jurisdiction_sources(jurisdiction_key,source_url,source_version,effective_from,checksum,retrieved_at)
  VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(jurisdiction_key,source_version,checksum) DO UPDATE SET retrieved_at=EXCLUDED.retrieved_at RETURNING id`,[jurisdiction.jurisdiction,jurisdiction.source_url,jurisdiction.fee_schedule_version,jurisdiction.effective_at,jurisdiction.checksum||jurisdiction.fee_schedule_version,jurisdiction.verified_at]);const result=await client.query(`INSERT INTO claim_guides(tenant_id,user_id,case_id,idempotency_key,jurisdiction_source_id,owner_id,disclaimer_accepted_at,consent,payload)
  VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING *`,[tenant,req.user.id,req.body.case_id||null,req.body.idempotency_key,source.rows[0].id,String(req.user.id),req.body.disclaimer_accepted_at,req.body.consent,{jurisdiction,case:req.body.case||{}}]);await client.query('COMMIT');res.status(201).json({...result.rows[0],informational_only:true});}catch(error){await client.query('ROLLBACK').catch(()=>{});next(error);}finally{client.release();}});

router.get('/:id',async(req,res,next)=>{try{const result=await pool.query('SELECT * FROM claim_guides WHERE id=$1 AND tenant_id=$2',[req.params.id,tenantOf(req)]);if(!result.rows[0])return res.status(404).json({error:'Guide not found'});res.json({...result.rows[0],informational_only:true});}catch(error){next(error);}});

router.post('/:id/transition',async(req,res,next)=>{const client=await pool.connect();try{const tenant=tenantOf(req);await client.query('BEGIN');const found=await client.query('SELECT * FROM claim_guides WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[req.params.id,tenant]);const current=found.rows[0];if(!current){await client.query('ROLLBACK');return res.status(404).json({error:'Guide not found'});}if(Number(req.body.version)!==current.version){await client.query('ROLLBACK');return res.status(409).json({error:'Stale workflow version'});}validateTransition(current.stage,req.body.to_stage,{...req.body.context,role:req.user.role||'claimant',actorId:String(req.user.id),ownerId:current.owner_id});const result=await client.query('UPDATE claim_guides SET stage=$1,version=version+1,assigned_to=COALESCE($2,assigned_to),updated_at=NOW() WHERE id=$3 RETURNING *',[req.body.to_stage,req.body.assigned_to||null,current.id]);const receipt=req.body.context?.providerReceipt;if(receipt?.provider&&receipt?.receipt_id)await client.query(`INSERT INTO claim_integration_deliveries(tenant_id,guide_id,provider,operation,idempotency_key,status,receipt) VALUES($1,$2,$3,$4,$5,'acknowledged',$6) ON CONFLICT(tenant_id,provider,idempotency_key) DO NOTHING`,[tenant,current.id,receipt.provider,req.body.to_stage,receipt.receipt_id,receipt]);await client.query('INSERT INTO claim_workflow_audit(tenant_id,guide_id,actor_id,action,from_stage,to_stage,payload) VALUES($1,$2,$3,$4,$5,$6,$7)',[tenant,current.id,String(req.user.id),'guide.transitioned',current.stage,req.body.to_stage,req.body.context||{}]);await client.query('COMMIT');res.json({...result.rows[0],informational_only:true});}catch(error){await client.query('ROLLBACK').catch(()=>{});next(error);}finally{client.release();}});
module.exports=router;
